config/routes.rb
Kissafrog::Application.routes.draw do
  
  get "showuser/index"

  match "/showuser/show/:id" => "showuser#show"

  root :to => 'info#index'
  resources :descs
  get "conversation/create"
  put "conversation/create"

  resources :saysomethings

  get "profile/index"
  get "conversation/justsend"
  resources :albums

  get "info/index"
  get "profile/index"
   
  devise_for :users

   

end

app/models/saysomething.rb
class Saysomething < ActiveRecord::Base
  attr_accessible :headlines, :interests, :say, :user_id
  belongs_to :user
end

app/controllers/saysomethings_controller.rb
class SaysomethingsController < ApplicationController
  # GET /saysomethings
  # GET /saysomethings.json
  before_filter :choose_user
  
  def index
    @saysomethings = @user.saysomething.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @saysomethings }
    end
  end

  # GET /saysomethings/1
  # GET /saysomethings/1.json
  def show
    @saysomething = @user.saysomething

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @saysomething }
    end
  end

  # GET /saysomethings/new
  # GET /saysomethings/new.json
  def new
    
    @saysomething = @user.build_saysomething(params[:saysomething])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @saysomething }
    end
  end

  # GET /saysomethings/1/edit
  def edit
   
    if @user.saysomething
      
      @saysomething = @user.saysomething

       respond_to do |format|
         format.js {}
          format.html {}# new.html.erb
          format.xml  { render :xml => @user.saysomething }
        end
        

    
    else
        respond_to do |format|

          format.html {redirect_to :controller => "saysomething", :action => "new" }
        end

      end
  end

  # POST /saysomethings
  # POST /saysomethings.json
  def create
    @saysomething = @user.create_saysomething(params[:saysomething])

    respond_to do |format|
      if @saysomething.save
        format.html { redirect_to @saysomething, notice: 'Saysomething was successfully created.' }
        format.json { render json: @saysomething, status: :created, location: @saysomething }
      else
        format.html { render action: "new" }
        format.json { render json: @saysomething.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /saysomethings/1
  # PUT /saysomethings/1.json
  def update
    @saysomething = @user.saysomething

    respond_to do |format|
      if @saysomething.update_attributes(params[:saysomething])
        format.html { redirect_to @saysomething, notice: 'Saysomething was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @saysomething.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saysomethings/1
  # DELETE /saysomethings/1.json
  def destroy
    @saysomething = @user.saysomething.find(params[:id])
    @saysomething.destroy

    respond_to do |format|
      format.html { redirect_to saysomethings_url }
      format.json { head :no_content }
    end
  end
  
  private
     def choose_user
        @user = current_user
     end
     
end

app/helpers/saysomethings_helper.rb
module SaysomethingsHelper
end

app/views/saysomethings/_form.html.erb
<%= form_for(@saysomething) do |f| %>
  <% if @saysomething.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saysomething.errors.count, "error") %> prohibited this saysomething from being saved:</h2>

      <ul>
      <% @saysomething.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headlines %><br />
    <%= f.text_field :headlines %>
  </div>
  <div class="field">
    <%= f.label :say %><br />
    <%= f.text_area :say %>
  </div>
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_field :interests %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saysomethings/edit.html.erb
<h1>Editing saysomething</h1>

<%= render 'form' %>

<%= link_to 'Show', @saysomething %> |
<%= link_to 'Back', saysomethings_path %>

app/views/saysomethings/index.html.erb
<h1>Listing saysomethings</h1>

<table>
  <tr>
    <th>Headlines</th>
    <th>Say</th>
    <th>Interests</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @saysomethings.each do |saysomething| %>
  <tr>
    <td><%= saysomething.headlines %></td>
    <td><%= saysomething.say %></td>
    <td><%= saysomething.interests %></td>
    <td><%= saysomething.user_id %></td>
    <td><%= link_to 'Show', saysomething %></td>
    <td><%= link_to 'Edit', edit_saysomething_path(saysomething) %></td>
    <td><%= link_to 'Destroy', saysomething, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Saysomething', new_saysomething_path %>

app/views/saysomethings/new.html.erb
<h1>New saysomething</h1>

<%= render 'form' %>

<%= link_to 'Back', saysomethings_path %>

app/views/saysomethings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Headlines:</b>
  <%= @saysomething.headlines %>
</p>

<p>
  <b>Say:</b>
  <%= @saysomething.say %>
</p>

<p>
  <b>Interests:</b>
  <%= @saysomething.interests %>
</p>

<p>
  <b>User:</b>
  <%= @saysomething.user_id %>
</p>


<%= link_to 'Edit', edit_saysomething_path(@saysomething) %> |
<%= link_to 'Back', saysomethings_path %>