config/routes.rb
Kissafrog::Application.routes.draw do
  
  get "showuser/index"

  match "/showuser/show/:id" => "showuser#show"

  root :to => 'info#index'
  resources :descs
  get "conversation/create"
  put "conversation/create"

  resources :saysomethings

  get "profile/index"
  get "conversation/justsend"
  resources :albums

  get "info/index"
  get "profile/index"
   
  devise_for :users

   

end

app/models/desc.rb
class Desc < ActiveRecord::Base
  attr_accessible :bodytype, :drink, :drug, :education, :ethnicity, :eye, :hair, :height, :kids, :language, :longestrelation, :marital, :pets, :profession, :religion, :smoke, :wantkids
  
  def height_options
      heights = Hash.new

      for n in 48..84
        feet = (n/12).floor
        inches = n % 12
        heights[n] = "#{feet}'#{inches}''"
      end

      return heights.to_a.sort.map { |h| h.reverse }
  end
end

app/controllers/descs_controller.rb
class DescsController < ApplicationController
  # GET /descs
  # GET /descs.json
  def index
    @descs = Desc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @descs }
    end
  end

  # GET /descs/1
  # GET /descs/1.json
  def show
    @desc = Desc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @desc }
    end
  end

  # GET /descs/new
  # GET /descs/new.json
  def new
    @desc = Desc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @desc }
    end
  end

  # GET /descs/1/edit
  def edit
    @desc = Desc.find(params[:id])
  end

  # POST /descs
  # POST /descs.json
  def create
    @desc = Desc.new(params[:desc])

    respond_to do |format|
      if @desc.save
        format.html { redirect_to @desc, notice: 'Desc was successfully created.' }
        format.json { render json: @desc, status: :created, location: @desc }
      else
        format.html { render action: "new" }
        format.json { render json: @desc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /descs/1
  # PUT /descs/1.json
  def update
    @desc = Desc.find(params[:id])

    respond_to do |format|
      if @desc.update_attributes(params[:desc])
        format.html { redirect_to @desc, notice: 'Desc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @desc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descs/1
  # DELETE /descs/1.json
  def destroy
    @desc = Desc.find(params[:id])
    @desc.destroy

    respond_to do |format|
      format.html { redirect_to descs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/descs_helper.rb
module DescsHelper
end

app/views/descs/_form.html.erb
<%= form_for(@desc) do |f| %>
  <% if @desc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desc.errors.count, "error") %> prohibited this desc from being saved:</h2>

      <ul>
      <% @desc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :bodytype %><br />
    <%= f.text_field :bodytype %>
  </div>
  <div class="field">
    <%= f.label :eye %><br />
    <%= f.text_field :eye %>
  </div>
  <div class="field">
    <%= f.label :hair %><br />
    <%= f.text_field :hair %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br />
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :religion %><br />
    <%= f.text_field :religion %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :profession %><br />
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :marital %><br />
    <%= f.text_field :marital %>
  </div>
  <div class="field">
    <%= f.label :longestrelation %><br />
    <%= f.number_field :longestrelation %>
  </div>
  <div class="field">
    <%= f.label :kids %><br />
    <%= f.text_field :kids %>
  </div>
  <div class="field">
    <%= f.label :wantkids %><br />
    <%= f.text_field :wantkids %>
  </div>
  <div class="field">
    <%= f.label :pets %><br />
    <%= f.text_field :pets %>
  </div>
  <div class="field">
    <%= f.label :smoke %><br />
    <%= f.text_field :smoke %>
  </div>
  <div class="field">
    <%= f.label :drink %><br />
    <%= f.text_field :drink %>
  </div>
  <div class="field">
    <%= f.label :drug %><br />
    <%= f.text_field :drug %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/descs/edit.html.erb
<h1>Editing desc</h1>

<%= render 'form' %>

<%= link_to 'Show', @desc %> |
<%= link_to 'Back', descs_path %>

app/views/descs/index.html.erb
<h1>Listing descs</h1>

<table>
  <tr>
    <th>Height</th>
    <th>Bodytype</th>
    <th>Eye</th>
    <th>Hair</th>
    <th>Ethnicity</th>
    <th>Religion</th>
    <th>Education</th>
    <th>Profession</th>
    <th>Marital</th>
    <th>Longestrelation</th>
    <th>Kids</th>
    <th>Wantkids</th>
    <th>Pets</th>
    <th>Smoke</th>
    <th>Drink</th>
    <th>Drug</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @descs.each do |desc| %>
  <tr>
    <td><%= desc.height %></td>
    <td><%= desc.bodytype %></td>
    <td><%= desc.eye %></td>
    <td><%= desc.hair %></td>
    <td><%= desc.ethnicity %></td>
    <td><%= desc.religion %></td>
    <td><%= desc.education %></td>
    <td><%= desc.profession %></td>
    <td><%= desc.marital %></td>
    <td><%= desc.longestrelation %></td>
    <td><%= desc.kids %></td>
    <td><%= desc.wantkids %></td>
    <td><%= desc.pets %></td>
    <td><%= desc.smoke %></td>
    <td><%= desc.drink %></td>
    <td><%= desc.drug %></td>
    <td><%= desc.language %></td>
    <td><%= link_to 'Show', desc %></td>
    <td><%= link_to 'Edit', edit_desc_path(desc) %></td>
    <td><%= link_to 'Destroy', desc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Desc', new_desc_path %>

app/views/descs/new.html.erb
<h1>New desc</h1>

<%= render 'form' %>

<%= link_to 'Back', descs_path %>

<center>
<a href="#" id="editgoal" data-type="text" data-pk="191" data-url="/post" data-original-title="edit">test</a>

</center>

app/views/descs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Height:</b>
  <%= @desc.height %>
</p>

<p>
  <b>Bodytype:</b>
  <%= @desc.bodytype %>
</p>

<p>
  <b>Eye:</b>
  <%= @desc.eye %>
</p>

<p>
  <b>Hair:</b>
  <%= @desc.hair %>
</p>

<p>
  <b>Ethnicity:</b>
  <%= @desc.ethnicity %>
</p>

<p>
  <b>Religion:</b>
  <%= @desc.religion %>
</p>

<p>
  <b>Education:</b>
  <%= @desc.education %>
</p>

<p>
  <b>Profession:</b>
  <%= @desc.profession %>
</p>

<p>
  <b>Marital:</b>
  <%= @desc.marital %>
</p>

<p>
  <b>Longestrelation:</b>
  <%= @desc.longestrelation %>
</p>

<p>
  <b>Kids:</b>
  <%= @desc.kids %>
</p>

<p>
  <b>Wantkids:</b>
  <%= @desc.wantkids %>
</p>

<p>
  <b>Pets:</b>
  <%= @desc.pets %>
</p>

<p>
  <b>Smoke:</b>
  <%= @desc.smoke %>
</p>

<p>
  <b>Drink:</b>
  <%= @desc.drink %>
</p>

<p>
  <b>Drug:</b>
  <%= @desc.drug %>
</p>

<p>
  <b>Language:</b>
  <%= @desc.language %>
</p>


<%= link_to 'Edit', edit_desc_path(@desc) %> |
<%= link_to 'Back', descs_path %>