config/routes.rb
Kissafrog::Application.routes.draw do
  
  get "showuser/index"

  match "/showuser/show/:id" => "showuser#show"

  root :to => 'info#index'
  resources :descs
  get "conversation/create"
  put "conversation/create"

  resources :saysomethings

  get "profile/index"
  get "conversation/justsend"
  resources :albums

  get "info/index"
  get "profile/index"
   
  devise_for :users

   

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :setting, :user_id
  
  attr_accessible :avatar
  attr_accessible :crop_x, :crop_y, :crop_w, :crop_h
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  AVATAR_SW = 155
  AVATAR_SH = 155
  AVATAR_NW = 340
  AVATAR_NH = 340

  has_attached_file :avatar,
        :styles => {
                    :original => {:geometry => "#{AVATAR_NW}x#{AVATAR_NH}>"},
                    :normal => {:geometry => "#{AVATAR_NW}x#{AVATAR_NH}>",  :processors => [:jcropper]},
                     :small => { :geometry => "#{AVATAR_SW}x#{AVATAR_SH}#"}, 
                     :medium => {:geometry =>  "700x700>"}, :thumb => {:geometry => "200x200>" }
                      
}
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png']



  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  
  private

  def reprocess_avatar
    avatar.reprocess!
  end
  
  belongs_to :user
  
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  layout 'album'
  before_filter :getcurrentuser
  
  def index
    
    @albums = @user.albums.all

    respond_to do |format|
      format.html # index.html.erb

      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
   
    @album = @user.albums.find(params[:id])

    respond_to do |format|
         
      format.html # show.html.erb
      format.js { render 'show'}
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
     
    @album = @user.albums.new
     respond_to do |format|
        format.js { render 'new' }
        format.html # show.html.erb
      end
  end

  # GET /albums/1/edit
  def edit
    
    @album = @user.albums.find(params[:id])
   
      if @album
         
         render :action => 'cropping'

     else
       render :action => 'new'
     end
  end

  # POST /albums
  # POST /albums.json
  def create
          
    @album = @user.albums.new(params[:album])
    
    if @album.save
       flash[:notice] = 'User was successfully created.'
       if params[:album][:avatar].blank?
         redirect_to @album
       else
        
         render :action => 'cropping'
       end
     else
       render :action => 'new'
     end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
       
    @album = @user.albums.find(params[:id])
    respond_to do |format|
       format.js { render 'new' }
       format.html{
     if @album.update_attributes params[:album]
        @album.avatar.reprocess!
        flash[:notice] = 'User was successfully updated.'
        if params[:album][:avatar].blank?
          redirect_to @album
        else
          
          render :action => 'cropping'
        end
      else
        render :action => "edit"
      end}
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy

    @album = @user.albums.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
  
  private
  def getcurrentuser
    @user = current_user
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :html => { :multipart => true } do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</br>
</br>
  <p><%= f.file_field :avatar %></p>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :setting %><br />
    <%= f.check_box :setting %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/cropping.html.erb
<p>
  <b>Name:</b>
  <%=h @album.description %>
</p>

<p>
  <b>Avatar:</b>
   
  <%= image_tag @album.avatar.url(:original), :id => 'cropbox' %>
<div style="width:<%= Album::AVATAR_SW %>px;height:<%= Album::AVATAR_SH %>px;overflow:hidden">
  <%= image_tag @album.avatar.url(:original), :id => 'preview' %>
</div>
</p>

<%= form_for @album do |f| %>
  <%= f.text_field :crop_x, :id => 'crop_x' %><br />
  <%= f.text_field :crop_y, :id => 'crop_y' %><br />
  <%= f.text_field :crop_w, :id => 'crop_w' %><br />
  <%= f.text_field :crop_h, :id => 'crop_h' %><br />
  <%= f.submit "Crop!" %>
<% end %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>


<script>
  function showPreview(coords)
  {
    var rx = <%= Album::AVATAR_SW %> / coords.w;
    var ry = <%= Album::AVATAR_SH %> / coords.h;
    var ratio = <%= @album.avatar_geometry(:original).width %> / <%= @album.avatar_geometry(:original).width %>;

    $('#preview').css({
      width: Math.round(rx * <%= @album.avatar_geometry(:original).width.to_i %>) + 'px',
      height: Math.round(ry * <%= @album.avatar_geometry(:original).height.to_i %>) + 'px',
      marginLeft: '-' + Math.round(rx * coords.x) + 'px',
      marginTop: '-' + Math.round(ry * coords.y) + 'px'
    });
    $('#crop_x').val(Math.round(coords.x * ratio));
    $('#crop_y').val(Math.round(coords.y * ratio));
    $('#crop_w').val(Math.round(coords.w * ratio));
    $('#crop_h').val(Math.round(coords.h * ratio));
  }

  $(function() {
    $('#cropbox').Jcrop({
        onSelect: showPreview,
        onChange: showPreview,
        setSelect:   [0, 0, 240, 240 ],
        aspectRatio: <%= Album::AVATAR_SW %>/<%= Album::AVATAR_SH %>
      });
  });
</script>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>User</th>
    <th>Description</th>
    <th>Setting</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
	  <td> <%= image_tag album.avatar.url(:normal) %></td>
    <td><%= album.user_id %></td>
    <td><%= album.description %></td>
    <td><%= album.setting %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/new.js.erb
<%= add_gritter("This is a notification just for you!", :title => "You have mail!", :image => "../assets/images/trees.jpg") %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>


	 
	<p>
	  <b>Avatar:</b>
	  <%= image_tag @album.avatar.url(:normal) %>
	</p>
	
<p>
  <b>User:</b>
  <%= @album.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>

<p>
  <b>Setting:</b>
  <%= @album.setting %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/albums/show.js.erb
alert("this works!!");