config/routes.rb
Kissafrog::Application.routes.draw do
  
  get "showuser/index"

  match "/showuser/show/:id" => "showuser#show"

  root :to => 'info#index'
  resources :descs
  get "conversation/create"
  put "conversation/create"

  resources :saysomethings

  get "profile/index"
  get "conversation/justsend"
  resources :albums

  get "info/index"
  get "profile/index"
   
  devise_for :users

   

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  

  
  def index
    @user = current_user
        @albums = @user.albums.all
        @numpic = (8 - @albums.count)
        @mainpic = @user.albums.where(:setting => true)
        
    @saysomething = @user.saysomething
        
  end

  
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/_mypics.html.erb
<div id="mainphoto">
	<div id="mainphotoselect">
<% @mainpic.each do |mainpic| %>
	   <%= image_tag mainpic.avatar.url(:normal) %>
<% end %>	
	</div>
</div>

<div id="otherpics">
	<div id="otherpicsselect">
<% @albums.each do |album| %>
  <tr>
	  <td> <%= image_tag album.avatar.url(:small) %></td>

    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
	</div>
</div>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/info/index.html.erb
<div id="container"> <!--div of main container-->
	<div id="header"> <!--div of header-->
		<!-- put logo in -->
		

				<ul id="topnav">
    				<li>About</li>
   					<li>Tour</li>
   					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>
				




		</div><!--div header ends here-->
		
</br>
		<div id = "sectionpic">

			<div id = "mainpic">
				<div id= "themainpic">
					<% @mainpic.each do |mainpic| %>
					
						    <div id="box-1" class="box">  
						     <td>  <%= image_tag mainpic.avatar.url(:normal) %></td>  
						        <span class="caption simple-caption">  
						        <p>Simple Caption</p>  
						        </span>  
						    </div>
						  
					<% end %>
				</div>

			</div>

			<div id= "many_small_pics">
        		<div id="mainwrapper">
				
				<% @albums.each do |album| %>
				 
				    <div id="box-1" class="box">  
				     <td> <%= image_tag album.avatar.url(:normal) %></td>  
				        <span class="caption simple-caption">  
				        <p>Simple Caption</p>  
				        </span>  
				    </div>  
				<% end %>

		
			<%	for i in 0..(@numpic-1) %>

				 
				    <div id="box-1" class="box">  
				     <td> <%= image_tag 'frog.jpg' %> </td>  
				        <span class="caption simple-caption">  
				        <p>Simple Caption</p>  
				        </span>  
				    </div>  
				<% end %>
    
				</div> <!-- end of #mainwrapper-->
<%= link_to 'Edit your pictures', :controller => 'albums', :action => 'index' %>
		     </div>
		</div>

		<div class = "sectionpause">
			</br>
		</div>

		<div id= "sectiondescription">
			<div id = "description_up">
			<h1>	About me: </h1>
			</div>
			<div id = "description">
				<p>
				  <h1>Headlines:</h1>
				  <%= @saysomething.headlines %>
				</p>

				<p>
				  <h1>Say:</h1>
				  <%= @saysomething.say %>
				</p>

				<p>
				  <h1>Interests:</h1>
			<div class= 'editable editable-click'>
				<div id ='saysomething'>
						
				  <%= @saysomething.interests  %>
				</div>
				</div>
				</p>
				
				<center>


				</center>
				
				<%= link_to 'Edit', edit_saysomething_path(@saysomething), id: 'editgoal', class: 'editable editable-click' %>
			</div>
		</div>

		<div class = "sectionpause">
		</div>

		<div id= "sectionprofileinfo">
			<div id= "profile_up">
			</div>
			<div id= "profile">
			</div>
		</div>

		<div class = "sectionpause">
		</div>

		<div id= "footer">
		</div>
		</br>

</div>


<script type="text/javascript">
$.fn.editable.defaults.mode = 'popup';
$('#saysomething').editable({
    type: 'text',
	ajaxOptions: {
	    type: 'put',
	    dataType: 'html',
	   
	},
	
    params: function(params) {
	    //originally params contain pk, name and value
	   	 alert(params.value);
	    params.saysomething = {id: <%= @saysomething.id %> , interests: params.value };

	    return params;
	},
    pk: {id: 'interests'},
    url: '/saysomethings/<%= @saysomething.id %>',
    title: 'Enter username',

});
</script>